name: ml-tdd-example workflow
on:
  push:
    branches: [ "main", "wip", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          echo $CONDA
          echo $PWD
          ls -alh

      - name: Install dependencies
        run: |
          conda env update --prune -f env_configs/environment_cpu.yml --name base
          pip-compile requirements/requirements.in && pip-compile requirements/requirements-dev.in
          pip install -r requirements/requirements.txt && pip install -r requirements/requirements-dev.txt
          python setup.py install

      - name: Tests
        run: |
          python -m pytest --cov mwrapper -v --junitxml=junit/test-results.xml
          # converage report

      - name: Upload Test results
        uses: actions/upload-artifact@main
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: always()

      - name: Statistics
        if: success()
        run: |
          coverage report
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: always()
        # see: https://github.com/actions/toolkit/issues/399
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: cpu,pytest
          name: Base-coverage
          fail_ci_if_error: false
